//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ÖğrenciNotMVC.Models.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ogrenciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Ogrenciler()
        {
            this.Tbl_Not = new HashSet<Tbl_Not>();
        }
    
        public int OgrenciId { get; set; }
        public string OgrenciAd { get; set; }
        public string OgrenciSoyad { get; set; }
        public string OgrenciFotograf { get; set; }
        public string OgrenciCinsiyet { get; set; }
        public Nullable<byte> OgrenciKulup { get; set; }
    
        public virtual Tbl_Kulup Tbl_Kulup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Not> Tbl_Not { get; set; }
    }
}
